"""add user roles table

Revision ID: ab7d744ed557
Revises: init_tables
Create Date: 2025-05-24 20:33:11.884179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab7d744ed557'
down_revision: Union[str, None] = 'init_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('access_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('access_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_apis_id'), 'apis', ['id'], unique=False)
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='菜单名称',
               existing_nullable=False)
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=20),
               comment='菜单类型',
               existing_nullable=False)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单路径',
               existing_nullable=False)
    op.alter_column('menus', 'component',
               existing_type=sa.VARCHAR(length=100),
               comment='组件路径',
               existing_nullable=False)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment='图标',
               existing_nullable=True)
    op.alter_column('menus', 'order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               comment='是否隐藏',
               existing_nullable=True)
    op.alter_column('menus', 'keepalive',
               existing_type=sa.BOOLEAN(),
               comment='是否缓存',
               existing_nullable=True)
    op.alter_column('menus', 'redirect',
               existing_type=sa.VARCHAR(length=200),
               comment='重定向',
               existing_nullable=True)
    op.alter_column('menus', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True)
    op.alter_column('menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('menus', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True)
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.drop_column('role_apis', 'updated_at')
    op.drop_column('role_apis', 'created_at')
    op.drop_column('role_menus', 'updated_at')
    op.drop_column('role_menus', 'created_at')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('tenant_permissions', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True)
    op.create_index(op.f('ix_tenant_permissions_id'), 'tenant_permissions', ['id'], unique=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_tenant_permissions_id'), table_name='tenant_permissions')
    op.alter_column('tenant_permissions', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('role_menus', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_menus', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_apis', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_apis', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.alter_column('menus', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('menus', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('menus', 'redirect',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='重定向',
               existing_nullable=True)
    op.alter_column('menus', 'keepalive',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否缓存',
               existing_nullable=True)
    op.alter_column('menus', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否隐藏',
               existing_nullable=True)
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='图标',
               existing_nullable=True)
    op.alter_column('menus', 'component',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='组件路径',
               existing_nullable=False)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单路径',
               existing_nullable=False)
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='菜单类型',
               existing_nullable=False)
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'updated_at')
    op.drop_index(op.f('ix_apis_id'), table_name='apis')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.alter_column('access_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('access_logs', 'updated_at')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
